name: Verify Lint

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest
    env:
      MIX_ENV: test
    strategy:
      matrix:
        elixir: [1.17]
        otp: [27]
    steps:
      - name: "Checkout Code"
        uses: actions/checkout@v4

      - name: "Setup Elixir"
        uses: erlef/setup-elixir@v1
        with:
          elixir-version: ${{ matrix.elixir }}
          otp-version: ${{ matrix.otp }}

      - name: "Cache Mix dependencies"
        uses: actions/cache@v4
        id: mix-cache-lint
        with:
          path: deps
          key: ${{ runner.os }}-${{ matrix.otp }}-${{ matrix.elixir }}-mix-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}

      - name: Install Mix Dependencies
        if: steps.mix-cache-lint.outputs.cache-hit != 'true'
        run: mix deps.get

      - name: ===> CREDO LINT
        run: mix credo --strict
